### PR TITLE
Build docs with nightly

### PR DESCRIPTION
**Pull request by wagenet**

### CODE REVIEW

**Comment by wagenet** [comment]
@chancancode should be straight-forward.

**Comment by wagenet** [comment]
The [warning messages](https://travis-ci.com/tildeio/libcruby-sys/jobs/145342275#L547) are proof that it's working.

**Comment by wagenet** [comment]
@chancancode docs build without nightly, they just don't crosslink correctly. Given how non-ideal it seemed to have crosslinks like `[``String``](static.rb_cString.html)` I thought it was worth it to be able to do `[String](rb_cString)` or even `[``ID``]` instead of `[``ID``](struct.ID.html)`.

**Comment by chancancode** [comment]
:+1: do you happen to have a link to the tracking issue?

**Comment by wagenet** [comment]
https://github.com/rust-lang/rust/issues/43466

**Pull request merged**
