### PR TITLE
Potential improvement for Ruby C enums

### PR DESCRIPTION
**Pull request by wagenet**
The big downside here is that you have to call `to_c` on your enums.

I could also see us making an internal macro to implement this for multiple different Ruby C enums.

### CODE REVIEW

**Comment by wagenet** [comment]
Possibly this is best done as sugar in Helix?

**Comment by chancancode** [comment]
Yeah, I think there is not much point doing it here at this layer. Once we are done with this the next thing I want to work on is extract a higher-level, safe library from Helix that does this kind of stuff.

**Comment by chancancode** [comment]
More specifically, I think it is good for this library to remain ~ runtime code free. Also for this particular case, since you are usually _passing_, not _receiving_ one of these (so you almost never `match` on one of these), a Rust enum doesn't buy you much.

**Comment by wagenet** [comment]
I'll leave the branch around for the moment in case we want to reference it later.

**Pull request closed without merging**
